#DB 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbp #수정 필요
    username: root
    password: tjdvy990626  #수정 필요
  sql:
    init:
      platform: mysql

  #JPA 설정
  jpa:
    database-platform:
    hibernate:
      ddl-auto: create #create / validate 확인

    #배포 할 때는 open-in-view false 설정
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
