#DB 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host}:${db.port}/${db.name} #수정 필요
    username: ${db.user}
    password: ${db.password} #수정 필요
  sql:
    init:
      mode: always
      platform: mysql
      data-locations: classpath:database/data.sql


  #JPA 설정
  jpa:
    database-platform:
    hibernate:
      ddl-auto: update #create / validate 확인

    #배포 할 때는 open-in-view false 설정
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
