version: "3.3"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "${DB_PORT}:3306"
    expose:
      # Opens port 3306 on the container
      - "${DB_PORT}"
      # Where our data will be persisted